### ISSUE TITLE
there is also \Uhhhhhhhh

### ISSUE THREAD

**Issue by monolifed** [MuhdNurHidayat/unicodeparser#10]
I ended up writing this from scratch but still the ones above 0xFFFF are not working.
``` lua
local sc = string.char
local fl = math.floor
local function utf8_enc(u)
	-- invalid codepoint
	if u >= 0xD800 and u <= 0xDFFF then return '?' end

	-- same
	if u < 0x80 then return sc(u) end

	
	local a, b, c, d
	if u < 0x800 then
		a = 0xC0 + fl(u / 0x40)
		b = 0x80 + (u % 0x40)
		return sc(a, b)
	end

	if u < 0x10000 then
		a = 0xE0 +  fl(u / 0x1000)
		b = 0x80 + (fl(u / 0x40) % 0x40)
		c = 0x80 + (u % 0x40)
		return sc(a, b, c)
	end

	-- 𠀋 \U0002000b becomes \u0000b somewhere after sending
	-- minetest.log still works as expected; shows the character in-game
	if u <= 0x10FFFF then
		a = 0xF0 + fl(u / 0x40000)
		b = 0x80 + (fl(u / 0x1000) % 0x40)
		c = 0x80 + (fl(u / 0x40) % 0x40)
		d = 0x80 + (u % 0x40)
		--return '?'
		minetest.log("error", sc(a, b, c, d))
		return sc(a, b, c, d)
	end

	return '?'
end

core.register_on_sending_chat_messages(function(message)
	message = message:gsub('\\U(%x%x%x%x%x%x%x%x)', function(u)
		--minetest.debug(u)
		return utf8_enc(tonumber(u, 16)) end
	)

	message = message:gsub('\\u(%x%x%x%x)', function(u)
		--minetest.debug(u)
		return utf8_enc(tonumber(u, 16)) end
	)

	-- \0xhhhh or \xhhhh
	message = message:gsub('\\0?x(%x%x%x%x)', function(u)
		--minetest.debug(u)
		return utf8_enc(tonumber(u, 16)) end
	)

	minetest.send_chat_message(message)
	return true
	end
)

-- command .uc for cli version
minetest.register_chatcommand("dummy", {
	params = "<arg>",
	description = "Dummy function",
	func = function(param)
		minetest.send_chat_message("Dummy TEXT")
	end
})

minetest.log('dummy parser loaded')


```

**Comment by mnh48** [comment]
That is because UTF-8 bytestring length is 4, it needs to be reimplement in different ways.
What it appear, "\U0002000b" is a **UTF-32** bytestring, not UTF-8.

The proper UTF-8 bytestring for that character is the surrogate quadpair of "\xf0\xa0\x80\x8b" but I don't know how to implement that.

See [this](http://unicode.scarfboy.com/?s=U%2B2000B)
![firefox_2018-08-07_13-06-18](https://user-images.githubusercontent.com/12217018/43755509-be06d1c0-9a42-11e8-84e3-b1e6305913ad.png)

and [this](https://codepoints.net/U+2000B?lang=en)
![firefox_2018-08-07_13-07-47](https://user-images.githubusercontent.com/12217018/43755535-e62db1e6-9a42-11e8-9498-920a0ad021af.png)

**Comment by monolifed** [comment]
- https://en.wikipedia.org/wiki/Escape_sequences_in_C  
\u and \U are the same, they are code points \u is used for the code points below 0x10000
- utf32 encoding keeps it unchanged (because it uses 4 bytes already but I think it is not relevant here)
- utf8_enc function above properly encodes it into said 4 bytes. That is why the character shows in the error message in the game. But it is truncated to its last 2 bytes somewhere in the game when sent as a chat message  
Sorry that I wasn't very clear in my first post.

**Comment by monolifed** [comment]
I think it might have something to do with Minetest. I created an issue:  
https://github.com/minetest/minetest/issues/7643

**Comment by mnh48** [comment]
Closing because it's upstream (minetest engine) issue, please follow minetest/minetest#7643 for discussions.
