### ISSUE TITLE
About other input boxes of Minetest

### ISSUE THREAD

**Issue by Hagb** [MuhdNurHidayat/unicodeparser#6]
This CSM is only for chat boxes. Is it possible to solve unicode inputting in all input boxes of Minetext by a CSM?

**Comment by Hagb** [comment]
I read minetest source code and found what the problem is.
I changed the source code by a very very bad way, which is so ugly and just written for a specific environment.
It can work well in my environment.

**Comment by mnh48** [comment]
Not possible because this CSM only use the send_message API...
Minetest GUI need to support it natively...

it actually seems to be working on some forks though, but I can't find which fork app that those players are using to write the texts...

**Comment by mnh48** [comment]
I'll close this since it's not directly related to unicodeparser itself (which only intended for the chat).

Further issue could be discussed at minetest/minetest#5226... as it seems to be the main issue that is used to discuss about unicode support anyway... also worth to discuss at minetest/minetest#6938 and it seems that they're trying to get upstream fix from irrlicht as mentioned at minetest/minetest#302

Do note that translation support on Android is also quite broken as reported at minetest/minetest#2030 and minetest/minetest#6093 ... while we can chat normally on the apps, the interface translation system itself was broken...
